### ISSUE TITLE
Not able to log in on Brave browser

### ISSUE THREAD

**Issue by vanstek** [A2B2-Studios/A2B2-Issue-Tracking#17]
Upon logging in, site refreshes as if I hadn't logged in.

Probably not worth worrying about at the moment, still works in Chrome for me.

**Comment by TerryDev** [comment]
Does Brave do weird stuff with JavaScript? I can't remember.

Anyways, make sure JS is enabled because with the new captcha system requires JS.

**Comment by vanstek** [comment]
Works now, not sure why.   :|
